export async function isEnvironmentRelated(message) {
  const keywords = [
    "climate",
    "weather",
    "environment",
    "global warming",
    "sustainability",
    "pollution",
    "carbon",
    "emissions",
    "temperature",
    "rain",
    "flood",
    "drought",
    "air quality",
    "greenhouse",
    "ozone",
    "weather",
    "rain",
    "sunny",
    "temperature",
    "forecast",
    "wind",
    "humidity",
    "season",
    "summer",
    "winter",
    "spring",
    "autumn",
    "fall",
    "climate in",
    "weather in",
  ];

  return keywords.some((word) => message.toLowerCase().includes(word));
}
